workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
image: docker
stages:
  - build
  - test
  - deploy

services:
  - docker:dind
      
build:
  stage: build
  script:
    - echo "This job builds docker-compose!"

test:
  stage: test
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "This job tests frontend application!"
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker ps -a
    - echo "Test begin! ----------------------------------------------------!"
    - date +%S
    - docker exec frontend sh -c "yarn test"
    - date +%S
    - echo "Test end! ----------------------------------------------------!"

deploy:
  stage: deploy
  script:
    - echo "This job deploys docker-compose!"
  environment: development

