workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
image: docker
stages:
  - build
  - test
  - deploy

services:
  - docker:dind
      
build:
  stage: build
  script:
    - echo "This job builds docker-compose!"

test:
  stage: test
  script:
  - echo "This job tests!"

deploy:
  stage: deploy
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "This job builds docker-compose!"
    - apk add --no-cache docker-compose
    - docker-compose up -d
    - docker ps -a
    - docker inspect frontend
    - docker exec frontend sh -c "yarn build"
    - docker exec frontend sh -c "ls"
    - docker exec backend sh -c "yarn build"
    - docker exec backend sh -c "ls"
  environment: production
