/// <reference types="cypress" />
describe('Testing all user features!', () => {
  it('Signup:', () => {
    //Signup
    cy.visit('http://localhost:5173/signup')
    cy.get('input[id=surname]').click({ force: true }).type('Max')
    cy.get('input[id=last_name]').click({ force: true }).type('Mustermann')
    cy.get('input[id=occupation]').click({ force: true }).type('Teacher')
    cy.get('input[id=age]').click({ force: true }).type('37')
    cy.get('input[id=email]').click({ force: true }).type('max.mustermann@gmail.com')
    cy.get('input[id=password]').click({ force: true }).type('1234abcd')
    cy.get('button').contains('Submit').click({ force: true })
    cy.url().should('include', '/profile')
    cy.get('#surname').contains('Max')
    cy.get('#last_name').contains('Mustermann')
    cy.get('#occupation').contains('Teacher')
    cy.get('#age').contains('37')
    cy.get('#email').contains('max.mustermann@gmail.com')
    //Signout
    cy.get('a').contains('Signout').click({ force: true })
    cy.url().should('include', '/signin')
    //Signin
    cy.get('input[id=email]').click({ force: true }).type('max.mustermann@gmail.com')
    cy.get('input[id=password]').click({ force: true }).type('1234abcd')
    cy.get('button').contains('Submit').click({ force: true })
    cy.url().should('include', '/profile')
    cy.get('#surname').contains('Max')
    cy.get('#last_name').contains('Mustermann')
    cy.get('#occupation').contains('Teacher')
    cy.get('#age').contains('37')
    cy.get('#email').contains('max.mustermann@gmail.com')
    //Profile Update
    cy.get('a').contains('Edit').click({ force: true })
    cy.get('input[id=surname]').click({ force: true }).type('Jeff')
    cy.get('input[id=last_name]').click({ force: true }).type('Jefferson')
    cy.get('input[id=occupation]').click({ force: true }).type('Janitor')
    cy.get('input[id=age]').click({ force: true }).type('53')
    cy.get('input[id=email]').click({ force: true }).type('jeff.jefferson@web.de')
    cy.get('a').contains('Update').click({ force: true })
    cy.get('#surname').contains('Jeff')
    cy.get('#last_name').contains('Jefferson')
    cy.get('#occupation').contains('Janitor')
    cy.get('#age').contains('53')
    cy.get('#email').contains('jeff.jefferson@web.de')
    //Profile Deletion
    cy.get('a').contains('Delete').click({ force: true })
    cy.url().should('include', '/signin')
    cy.get('input[id=email]').click({ force: true }).type('jeff.jefferson@web.de')
    cy.get('input[id=password]').click({ force: true }).type('1234abcd')
    cy.get('button').contains('Submit').click({ force: true })
    cy.url().should('include', '/signin')
  })
})